// SPDX-License-Identifier: CC0-1.0

//! Code generation tool for Bitcoin Core JSON-RPC API types.
//!
//! This tool reads an OpenRPC specification (as generated by Bitcoin Core v30+) and generates
//! Rust type definitions that can be used with the `corepc-types` crate.
//!
//! # Usage
//!
//! ```bash
//! cargo run --bin corepc-codegen -- --input OpenRPC.json --output types/src/v30 --version v30
//! ```

mod generator;
mod modules;
mod schema;

use std::fs;
use std::path::PathBuf;

use anyhow::{Context, Result};
use clap::Parser;

use crate::generator::GeneratorConfig;
use crate::modules::{generate_mod_rs, generate_modules};
use crate::schema::OpenRpcDocument;

/// Code generator for Bitcoin Core RPC types from OpenRPC specification.
#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// Path to the OpenRPC.json file.
    #[arg(short, long)]
    input: PathBuf,

    /// Output directory for generated files.
    #[arg(short, long)]
    output: PathBuf,

    /// Bitcoin Core version (e.g., "v30").
    #[arg(short = 'c', long = "core-version")]
    core_version: String,

    /// Only print what would be generated, don't write files.
    #[arg(long, default_value = "false")]
    dry_run: bool,

    /// Generate a single combined file instead of separate modules.
    #[arg(long, default_value = "false")]
    single_file: bool,
}

fn main() -> Result<()> {
    let args = Args::parse();

    // Read and parse the OpenRPC document
    let content = fs::read_to_string(&args.input)
        .with_context(|| format!("Failed to read input file: {:?}", args.input))?;

    let doc: OpenRpcDocument = serde_json::from_str(&content)
        .with_context(|| "Failed to parse OpenRPC document")?;

    println!(
        "Parsed OpenRPC document: {} ({})",
        doc.info.title, doc.info.version
    );
    println!("Found {} methods", doc.methods.len());

    // Generate modules
    let config = GeneratorConfig::default();
    let modules = generate_modules(&doc.methods, config);

    println!("Generated {} modules:", modules.len());
    for module in &modules {
        println!(
            "  - {}: {} types from {} methods",
            module.name,
            module.exports.len(),
            module.methods.len()
        );
    }

    if args.dry_run {
        println!("\n[DRY RUN] Would generate the following files:");
        for module in &modules {
            if !module.exports.is_empty() {
                println!("  - {}/{}.rs", args.output.display(), module.name);
            }
        }
        println!("  - {}/mod.rs", args.output.display());
        return Ok(());
    }

    // Create output directory
    fs::create_dir_all(&args.output)
        .with_context(|| format!("Failed to create output directory: {:?}", args.output))?;

    if args.single_file {
        // Generate a single combined file
        let mut combined = String::new();
        combined.push_str(&generate_mod_rs(&modules, &args.core_version));
        combined.push_str("\n// ============ Generated Types ============\n\n");

        for module in &modules {
            if !module.exports.is_empty() {
                combined.push_str(&format!("\n// --- {} ---\n\n", module.name));
                combined.push_str(&module.code);
            }
        }

        let output_path = args.output.join("generated.rs");
        fs::write(&output_path, &combined)
            .with_context(|| format!("Failed to write: {:?}", output_path))?;
        println!("Wrote: {:?}", output_path);
    } else {
        // Generate separate module files
        for module in &modules {
            if !module.exports.is_empty() {
                let output_path = args.output.join(format!("{}.rs", module.name));
                fs::write(&output_path, &module.code)
                    .with_context(|| format!("Failed to write: {:?}", output_path))?;
                println!("Wrote: {:?}", output_path);
            }
        }

        // Generate mod.rs
        let mod_rs = generate_mod_rs(&modules, &args.core_version);
        let mod_path = args.output.join("mod.rs");
        fs::write(&mod_path, &mod_rs)
            .with_context(|| format!("Failed to write: {:?}", mod_path))?;
        println!("Wrote: {:?}", mod_path);
    }

    println!("\nCode generation complete!");
    Ok(())
}
